name: Main.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Delete node_modules
        run: |
          rm -rf node_modules/

      - name: Update npm packages
        run: |
          npm update

      - name: Restart server
        run: |
          pm2 restart server.js
