name: Main.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: ['18.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd server/earnarsbackend
          npm install

      - name: Restart services
        run: |
          npm update
          pm2 stop 0
          pm2 startup server.js --env production
          pm2 save
          sudo service nginx restart
