name: Main.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
        run: | 
          cd server/earnarsbackend
          npm i       
          pm2 stop 1
          pm2 start 1
          pm2 save
          sudo service nginx restart 
    
    
