name: Main.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
    # - run: npm i
    # - run: npm run build

        run: | 
          cd server
          cd earnarsbackend
      - name: "Delete nodemodules"
        run: | 
          rm -rf node_modules/
      - name: "Delete nodemodules"
        run: | 
          npm update       
          pm2 stop 0
          pm2 start 0
          pm2 save
          sudo service nginx restart 
    
    
