name: main

on:
   push:
     branches: []
   pull_request:
      branches: []
    
    jobs:
      build:
         runs-on: self-hosted

    steps:
      -uses: actions/checkout@v2
      -name: Use Node.js ${{ matrix.node-version}}
       uses: actions/setup-node@v1
       with:
          node-version: ${{ matrix.node-version}}
      -run:
         npm i
         cd earnarsfile
         npm i
         npm run build
         
